# Имя вашего workflow, которое будет отображаться в интерфейсе GitHub Actions
name: API tests

# Указываем, когда будет запускаться данный workflow. Тригеры запуска автотестов
on:
  push:
    branches:
      - main  # Запускать workflow, когда будет сделан коммит в ветку main
  pull_request:
    branches:
      - main  # Запускать workflow, когда будет сделан pull  request в ветку main

# Определяем все шаги, которые должны быть выполнены в рамках работы с  тестами
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Clone test server repository
        run: git clone https://github.com/Nikita-Filonov/qa-automation-engineer-api-course.git

      - name: Install test server dependencies
        run: pip install -r qa-automation-engineer-api-course/requirements.txt

      - name: Start a test server
        env:
          APP_HOST: "http://localhost:8000"  # Устанавливаем адрес хоста сервера
          DATABASE_URL: "sqlite+aiosqlite:///./local.db" # Устанавливаем URL локальной базы данных
          JWT_ALGORITHM: "HS256" # Алгоритм для JWT токенов
          JWT_SECRET_KEY: "qa-automation-engineer-api-course-secret-key" # Секретный ключ для JWT
          JWT_ACCESS_TOKEN_EXPIRE: 1800 # Время жизни access token (в секундах)
          JWT_REFRESH_TOKEN_EXPIRE: 5184000 # Время жизни refresh token (в секундах)
        run: uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir ./qa-automation-engineer-api-course & # Запускаем сервер с указанными переменными окружения

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Обновляем pip до последней версии
          pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt
      
      - name: Run API tests with pytest and generate allure results
        run: |
          pytest -m regression --alluredir=./allure-results  # Запускаем тесты и генерируем результаты для Allure

      - name: Upload allure-results package
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: allure-results
          path: allure-results


  publish-report:
    if: always()
    runs-on: ubuntu-latest
    needs: [run-tests]

    steps:
      - name: Get allure history
        uses: actions/checkout@v6  # Опять клонируем репозиторий для получения истории отчётов
        if: always()  # Всегда выполняем этот шаг
        continue-on-error: true  # Если будет ошибка, продолжим выполнение
        with:
          ref: gh-pages  # Указываем ветку gh-pages для получения истории
          path: gh-pages  # Указываем путь, куда сохранить данные

      - name: Download allure results
        uses: actions/download-artifact@v7
        with:
          name: allure-results
          path: allure-results

      - name: Generates allure report with history
        uses: simple-elf/allure-report-action@v1.13  # Используем готовое решение для генерации Allure отчёта
        if: always()
        with:
          allure-results: allure-results  # Указываем каталог с результатами тестов
          allure-history: allure-history  # Указываем каталог для истории отчётов

      - name: Deploy report to GitHob Pages
        if: always()  # Выполняем всегда
        uses: peaceiris/actions-gh-pages@v4  # Используем GitHub Action для публикации отчёта на GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Токен для аутентификации на GitHub
          publish_branch: gh-pages  # Указываем, что отчёт будет опубликован в ветке gh-pages
          publish_dir: allure-history  # Указываем папку, которая будет опубликована на GitHub Pages
